from __future__ import annotations

from dataclasses import dataclass
import json
from typing import Any

from aiohttp import web

from homeassistant.components import frontend, panel_custom
from homeassistant.components.http import HomeAssistantView, StaticPathConfig
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er

from .const import DOMAIN, PANEL_NAME, PANEL_URL_PATH, STATIC_URL, VERSION

PLATFORMS: list[str] = []

SERVICE_EXAMPLES: dict[str, dict[str, Any]] = {
    "light.turn_on": {"brightness_pct": 70},
    "light.turn_off": {},
    "switch.turn_on": {},
    "switch.turn_off": {},
    "cover.open_cover": {},
    "cover.close_cover": {},
    "cover.set_cover_position": {"position": 50},
    "climate.set_temperature": {"temperature": 21},
    "climate.set_hvac_mode": {"hvac_mode": "heat"},
    "media_player.media_play": {},
    "media_player.media_pause": {},
    "media_player.volume_set": {"volume_level": 0.35},
    "fan.turn_on": {},
    "fan.turn_off": {},
    "lock.lock": {},
    "lock.unlock": {},
    "button.press": {},
    "input_button.press": {},
    "scene.turn_on": {},
    "automation.trigger": {"skip_condition": False},
}

DOMAIN_SERVICE_HINTS: dict[str, tuple[str, ...]] = {
    "light": ("turn_on", "turn_off", "toggle"),
    "switch": ("turn_on", "turn_off", "toggle"),
    "cover": ("open_cover", "close_cover", "stop_cover", "set_cover_position"),
    "climate": ("set_temperature", "set_hvac_mode", "turn_on", "turn_off"),
    "media_player": ("media_play", "media_pause", "volume_set", "turn_on", "turn_off"),
    "fan": ("turn_on", "turn_off", "toggle", "set_percentage"),
    "lock": ("lock", "unlock"),
    "button": ("press",),
    "input_button": ("press",),
    "scene": ("turn_on",),
    "automation": ("trigger", "turn_on", "turn_off"),
}


@dataclass(frozen=True)
class EntitySummary:
    entity_id: str
    name: str
    domain: str
    state: str
    device_id: str | None
    area_id: str | None


def _state_name(state_obj: Any) -> str:
    friendly = state_obj.attributes.get("friendly_name") if state_obj else None
    return str(friendly or state_obj.entity_id)


def _summarise_entity(hass: HomeAssistant, entity_id: str) -> EntitySummary | None:
    state_obj = hass.states.get(entity_id)
    if state_obj is None:
        return None

    registry = er.async_get(hass)
    entry = registry.async_get(entity_id)
    domain = entity_id.split(".", 1)[0]
    return EntitySummary(
        entity_id=entity_id,
        name=_state_name(state_obj),
        domain=domain,
        state=str(state_obj.state),
        device_id=entry.device_id if entry else None,
        area_id=entry.area_id if entry else None,
    )


def _serialise_service(domain: str, service_name: str, service_info: Any) -> dict[str, Any]:
    service_id = f"{domain}.{service_name}"
    if isinstance(service_info, dict):
        fields = service_info.get("fields") or {}
        name = service_info.get("name")
        description = service_info.get("description") or ""
    else:
        # hass.services.async_services() returns Service objects, not the
        # localized service-description dictionaries used by the services UI.
        # Keep this endpoint robust across HA versions by exposing the stable
        # service id and any fields only when a dict-like description is passed.
        fields = {}
        name = None
        description = ""
    example_data = SERVICE_EXAMPLES.get(service_id, {})
    return {
        "service": service_id,
        "name": name or service_name.replace("_", " ").title(),
        "description": description,
        "recommended": service_name in DOMAIN_SERVICE_HINTS.get(domain, ()),
        "fields": fields,
        "example_data": example_data,
    }


def _service_call_yaml(alias: str, entity_id: str, service: str, service_data: dict[str, Any]) -> str:
    lines = [
        f"alias: {alias}",
        "description: Generated by Action Explorer. Review before saving.",
        "triggers: []",
        "conditions: []",
        "actions:",
        f"  - action: {service}",
        "    target:",
        f"      entity_id: {entity_id}",
    ]
    if service_data:
        lines.append("    data:")
        for key, value in service_data.items():
            if value is None:
                rendered = "null"
            elif isinstance(value, bool):
                rendered = "true" if value else "false"
            elif isinstance(value, (int, float)):
                rendered = str(value)
            else:
                rendered = json.dumps(str(value))
            lines.append(f"      {key}: {rendered}")
    lines.extend(["mode: single", ""])
    return "\n".join(lines)


class ActionExplorerEntitiesView(HomeAssistantView):
    """Return searchable entity summaries."""

    url = "/api/action_explorer/entities"
    name = "api:action_explorer:entities"
    requires_auth = True

    async def get(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        query = str(request.query.get("q", "")).lower().strip()
        domain_filter = str(request.query.get("domain", "")).lower().strip()

        entities: list[dict[str, Any]] = []
        for entity_id in sorted(hass.states.async_entity_ids()):
            summary = _summarise_entity(hass, entity_id)
            if summary is None:
                continue
            haystack = f"{summary.entity_id} {summary.name}".lower()
            if query and query not in haystack:
                continue
            if domain_filter and summary.domain != domain_filter:
                continue
            entities.append(summary.__dict__)
            if len(entities) >= 250:
                break

        return self.json({"entities": entities})


class ActionExplorerActionsView(HomeAssistantView):
    """Return supported services and examples for one entity."""

    url = "/action_explorer/actions/{entity_id}"
    name = "api:action_explorer:actions"
    requires_auth = True

    async def get(self, request: web.Request, entity_id: str) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        summary = _summarise_entity(hass, entity_id)
        if summary is None:
            return self.json({"error": "entity_not_found", "entity_id": entity_id}, status_code=404)

        services = hass.services.async_services().get(summary.domain, {})
        actions = [
            _serialise_service(summary.domain, service_name, service_info)
            for service_name, service_info in sorted(services.items())
        ]
        actions.sort(key=lambda item: (not item["recommended"], item["service"]))

        return self.json({"entity": summary.__dict__, "actions": actions})


class ActionExplorerAutomationView(HomeAssistantView):
    """Generate a validated automation snippet for a service call."""

    url = "/action_explorer/automation"
    name = "api:action_explorer:automation"
    requires_auth = True

    async def post(self, request: web.Request) -> web.Response:
        hass: HomeAssistant = request.app["hass"]
        try:
            payload = await request.json()
        except ValueError:
            return self.json({"error": "invalid_json"}, status_code=400)
        if not isinstance(payload, dict):
            return self.json({"error": "payload_must_be_object"}, status_code=400)

        entity_id = payload.get("entity_id")
        service = payload.get("service")
        alias = payload.get("alias") or "Action Explorer generated automation"
        service_data = payload.get("service_data") or {}

        if not isinstance(entity_id, str) or "." not in entity_id:
            return self.json({"error": "invalid_entity_id"}, status_code=400)
        if _summarise_entity(hass, entity_id) is None:
            return self.json({"error": "entity_not_found", "entity_id": entity_id}, status_code=404)
        if not isinstance(service, str) or "." not in service:
            return self.json({"error": "invalid_service"}, status_code=400)
        if not isinstance(alias, str) or not alias.strip():
            return self.json({"error": "invalid_alias"}, status_code=400)
        if not isinstance(service_data, dict):
            return self.json({"error": "service_data_must_be_object"}, status_code=400)

        domain, service_name = service.split(".", 1)
        if not hass.services.has_service(domain, service_name):
            return self.json({"error": "service_not_found", "service": service}, status_code=404)
        if domain != entity_id.split(".", 1)[0] and domain not in {"homeassistant"}:
            return self.json(
                {"error": "service_domain_mismatch", "service": service, "entity_id": entity_id},
                status_code=400,
            )

        yaml = _service_call_yaml(alias.strip(), entity_id, service, service_data)
        return self.json(
            {
                "automation_yaml": yaml,
                "action": {"action": service, "target": {"entity_id": entity_id}, "data": service_data},
            }
        )


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up Action Explorer from a config entry."""
    await hass.http.async_register_static_paths(
        [
            StaticPathConfig(
                STATIC_URL,
                hass.config.path("custom_components/action_explorer/www"),
                cache_headers=True,
            )
        ]
    )

    hass.http.register_view(ActionExplorerEntitiesView)
    hass.http.register_view(ActionExplorerActionsView)
    hass.http.register_view(ActionExplorerAutomationView)

    await panel_custom.async_register_panel(
        hass,
        frontend_url_path=PANEL_URL_PATH,
        webcomponent_name=PANEL_NAME,
        sidebar_title="Action Explorer",
        sidebar_icon="mdi:gesture-tap-button",
        module_url=f"{STATIC_URL}/action-explorer-panel.js?v={VERSION}",
        embed_iframe=False,
        require_admin=False,
        config={"apiBase": "action_explorer"},
    )
    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload Action Explorer."""
    frontend.async_remove_panel(hass, PANEL_URL_PATH)
    return True
